User/Authentication service
JoseBueno30/laWiki pull request #26
Opened 2024-12-21 17:11 UTC by adriantd3

Este microservicio tiene principalmente la funcionalidad de verificar los tokens.

Si el token es válido, devuelve toda la información del token y del usuario.
Además, si es la primera vez que el usuario inicia sesión, añade su información a la base de datos.

---
En cuanto a los otros endpoints, la mayoría son restringidos. Es decir, necesitan las cabeceras user-email y admin de la request.
Si el usuario que hace la peticion no tiene los permisos, se le deniega el acceso

2024-12-22 18:52 UTC, JoseBueno30 requested changes
endpoint verify_token como PUT

2024-12-23 11:07 UTC, DavidBuenoCarmona commented
![image](https://github.com/user-attachments/assets/6a94f65d-3eb0-4d71-939b-2f7e199fb6f0)

Estos 3 endpoints son redundantes entre sí. Podemos dejar update info y que cambie la foto y el nombre a la vez, si el nombre no ha cambiado o la foto no ha cambiado, solo se verá el cambio en el que corresponda.

2024-12-23 12:36 UTC, adriantd3 commented
> ![image](https://private-user-images.githubusercontent.com/124664414/398143018-6a94f65d-3eb0-4d71-939b-2f7e199fb6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTc2MDMsIm5iZiI6MTczNDk1NzMwMywicGF0aCI6Ii8xMjQ2NjQ0MTQvMzk4MTQzMDE4LTZhOTRmNjVkLTNlYjAtNGQ3MS05MzliLTJmN2UxOTlmYjZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxMjM1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGI3NTg1ZDBlNWNmZGY3NTRlNDFmYjI2ZmQzNjJkNGM3OGJkZGE1YTA2Yjk0OGVkODJkOTI4YTg3ODY2MjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CZDCwJE2HaC7E0sT7ibKEJW7ZiYNgLcTnzf9EBUQars)
> 
> Estos 3 endpoints son redundantes entre sí. Podemos dejar update info y que cambie la foto y el nombre a la vez, si el nombre no ha cambiado o la foto no ha cambiado, solo se verá el cambio en el que corresponda.
> 
> Piensa en la aplicación cuando se van a llamar, tendrías que estar comprobando si han cambiado los 2 llame a update infor, si solo la foto, llamo a update foto, si solo el nombre llamo a update nombre.
> 
> Generalizándolo a update info nos sirve

Lo he hecho asi porque no sabía cómo iba a ser lo de cambiar la información del usuario en el front, si mediante un formulario o actualizando las cosas por separado. Se que es redundante pero lo he hecho por flexibilidad

2024-12-23 15:41 UTC, JoseBueno30 approved these changes

2024-12-23 15:42 UTC, merged